// <auto-generated />
namespace Nhom04_Jewelry.IdentityMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddHoTenRow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddHoTenRow));
        
        string IMigrationMetadata.Id
        {
            get { return "202312030852523_AddHoTenRow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
